name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - name: Check Scala format
      run: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - name: Build and Test
      run: sbt -v +test
